version: '3.8'
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: artweb
      MONGO_INITDB_ROOT_PASSWORD: elkindy
    ports:
      - 27017:27017
    volumes:
      - ./data/dump:/dump
  app:
    build: .
    image: 192.168.0.132:8087/nodemongoapp:6.0
    restart: always
    container_name: back
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - mongo-data:/path/to/mount/point

volumes:
  mongo-data: